'use client';
import { useState } from 'react';
import { submitBugReport } from '@/actions/feedback';
import logger from '@/lib/logger';

export default function BugReportPanel() {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState('');
  const [severity, setSeverity] = useState<'low' | 'normal' | 'high' | 'critical'>('normal');
  const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const send = async () => { setLoading(true); setMessage(''); const result = await submitBugReport({ title, description, severity, pageUrl: location.href, diagnostics: logger.getDiagnosticSnapshot() }); setMessage(result.success ? result.mailSent ? '反馈和脱敏诊断日志已提交，管理员已收到邮件提醒。' : `反馈与诊断日志已保存；${result.mailError ?? '管理员邮件提醒未发送'}。` : result.error ?? '提交失败'); if (result.success) { setTitle(''); setDescription(''); } setLoading(false); };
  return <section className="rounded-[12px] border border-[var(--card-border)] bg-[var(--card)] p-5"><div className="mb-4 flex items-center gap-2"><span className="material-icons-round text-[#EA4335]">bug_report</span><h2 className="text-sm font-semibold uppercase tracking-wider text-[var(--muted-foreground)]">Bug 反馈</h2></div><p className="mb-3 text-xs text-[var(--muted-foreground)]">提交时会附上已脱敏的网络、错误与操作轨迹，帮助管理员复现问题。</p><div className="space-y-3"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="问题标题" className="w-full rounded-lg border border-[var(--card-border)] bg-[var(--background)] px-3 py-2 text-sm" /><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="请描述复现步骤、预期结果和实际结果" rows={4} className="w-full rounded-lg border border-[var(--card-border)] bg-[var(--background)] px-3 py-2 text-sm" /><select value={severity} onChange={(e) => setSeverity(e.target.value as typeof severity)} className="rounded-lg border border-[var(--card-border)] bg-[var(--background)] px-3 py-2 text-sm"><option value="low">轻微</option><option value="normal">普通</option><option value="high">严重</option><option value="critical">紧急</option></select><button type="button" disabled={loading || title.trim().length < 3 || !description.trim()} onClick={send} className="ml-2 rounded-lg bg-[#EA4335] px-4 py-2 text-sm font-medium text-white disabled:cursor-not-allowed disabled:opacity-50">{loading ? '提交中…' : '提交反馈'}</button>{message && <p className="text-sm text-[var(--muted-foreground)]">{message}</p>}</div></section>;
}
