'use client';

import { useState } from 'react';
import { exportAllUserData, importSelectedData, previewDataImport, type DataArchive } from '@/actions/export';

type Preview = { table: string; incoming: number; local: number; changed: boolean };
export default function ExportDataPanel() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const [preview, setPreview] = useState<Preview[]>([]); const [archive, setArchive] = useState<DataArchive | null>(null); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState('');
  const download = (data: DataArchive, prefix: string) => { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `${prefix}-${new Date().toISOString().replace(/[:.]/g, '-')}.json`; link.click(); URL.revokeObjectURL(url); };
  const exportAll = async () => { setLoading(true); setError(''); try { download(await exportAllUserData(), 'jackyun-full-backup'); } catch (e) { setError(e instanceof Error ? e.message : '导出失败'); } finally { setLoading(false); } };
  const chooseFile = async (file?: File) => { if (!file) return; setLoading(true); setError(''); setMessage(''); try { const data = JSON.parse(await file.text()) as DataArchive; if ((data.version !== 1 && data.version !== 2) || !data.tables) throw new Error('不是 JackYun 完整备份文件'); const rows = await previewDataImport(data); setArchive(data); setPreview(rows); setSelected(rows.filter((row) => row.changed).map((row) => row.table)); } catch (e) { setError(e instanceof Error ? e.message : '无法读取备份'); } finally { setLoading(false); } };
  const apply = async () => { if (!archive || !selected.length) return; setLoading(true); setError(''); try { download(await exportAllUserData(), 'jackyun-pre-import-recovery'); const result = await importSelectedData(archive, selected as never); setMessage(`已先下载恢复快照；成功导入 ${result.imported.length} 类数据，空数据跳过 ${result.skipped.length} 类。`); } catch (e) { setError(e instanceof Error ? e.message : '导入失败；原数据与恢复文件均已保留'); } finally { setLoading(false); } };
  const toggle = (table: string) => setSelected((current) => current.includes(table) ? current.filter((value) => value !== table) : [...current, table]);
  return <div className="space-y-4"><div className="flex flex-wrap gap-3"><button onClick={exportAll} disabled={loading} className="rounded-lg border border-[var(--card-border)] px-4 py-2 text-sm font-medium hover:bg-[#4285F4]/5 disabled:opacity-50"><span className="material-icons-round mr-1 align-middle text-[#4285F4]">download</span>导出全部数据</button><label className="cursor-pointer rounded-lg bg-[#4285F4] px-4 py-2 text-sm font-medium text-white hover:bg-[#3367d6]"><span className="material-icons-round mr-1 align-middle">upload</span>选择备份导入<input type="file" accept="application/json,.json" className="hidden" onChange={(event) => chooseFile(event.target.files?.[0])} /></label></div><p className="text-xs text-[var(--muted-foreground)]">v2 完整备份带校验摘要，包括学习、题库、音乐、倒计时、专注、设置与旧模块同步数据；仍兼容 v1。导入前会自动下载恢复快照。</p>{preview.length > 0 && <div className="rounded-xl border border-[var(--card-border)]"><div className="flex items-center justify-between border-b border-[var(--card-border)] px-4 py-3"><p className="text-sm font-semibold">导入差异预览</p><div className="flex gap-2 text-xs"><button onClick={() => setSelected(preview.map((row) => row.table))} className="text-[#4285F4]">全选</button><button onClick={() => setSelected([])} className="text-[var(--muted-foreground)]">全不选</button></div></div><div className="max-h-64 overflow-y-auto">{preview.map((row) => <label key={row.table} className="flex cursor-pointer items-center gap-3 border-b border-[var(--card-border)] px-4 py-2.5 last:border-0"><input type="checkbox" checked={selected.includes(row.table)} onChange={() => toggle(row.table)} /><span className="flex-1 text-sm">{row.table}</span><span className="text-xs text-[var(--muted-foreground)]">备份 {row.incoming} · 当前 {row.local}</span></label>)}</div><div className="flex justify-end border-t border-[var(--card-border)] p-3"><button disabled={loading || !selected.length} onClick={apply} className="rounded-lg bg-[#34A853] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">备份并导入 {selected.length} 项</button></div></div>}{loading && <p className="text-sm text-[var(--muted-foreground)]">处理中…</p>}{error && <p className="rounded-lg bg-[#EA4335]/10 px-3 py-2 text-sm text-[#EA4335]">{error}</p>}{message && <p className="rounded-lg bg-[#34A853]/10 px-3 py-2 text-sm text-[#188038]">{message}</p>}</div>;
}
