export type ResourceCategory =
  | 'igcse'
  | 'alevel-cie'
  | 'alevel-edexcel'
  | 'ielts'
  | 'ai'
  | 'math-science'
  | 'computer'
  | 'courses'
  | 'language'
  | 'research'
  | 'tools';

export interface LearningResource {
  name: string;
  url: string;
  category: ResourceCategory;
  description: string;
  tags: string[];
  source: 'bookmark' | 'official' | 'added';
  featured?: boolean;
}

export const RESOURCE_CATEGORIES: { id: 'all' | ResourceCategory; label: string; icon: string }[] = [
  { id: 'all', label: '全部', icon: 'apps' },
  { id: 'igcse', label: 'IGCSE', icon: 'school' },
  { id: 'alevel-cie', label: 'A Level · CIE', icon: 'science' },
  { id: 'alevel-edexcel', label: 'A Level · Edexcel', icon: 'calculate' },
  { id: 'ielts', label: 'English · IELTS', icon: 'translate' },
  { id: 'ai', label: 'AI 助手', icon: 'smart_toy' },
  { id: 'math-science', label: '数学与科学', icon: 'functions' },
  { id: 'computer', label: 'Computer', icon: 'terminal' },
  { id: 'courses', label: '公开课程', icon: 'cast_for_education' },
  { id: 'language', label: '语言学习', icon: 'record_voice_over' },
  { id: 'research', label: '知识与论文', icon: 'manage_search' },
  { id: 'tools', label: '学习工具', icon: 'auto_awesome' },
];

export const LEARNING_RESOURCES: LearningResource[] = [
  {
    name: 'Best Exam Help',
    url: 'https://bestexamhelp.com/exam/cambridge-igcse/pp-igcse.php',
    category: 'igcse',
    description: '按科目与考试季整理 Cambridge IGCSE 历年真题，适合集中查找 question paper 与 mark scheme。',
    tags: ['Past Papers', 'Cambridge', '真题'],
    source: 'bookmark',
    featured: true,
  },
  {
    name: 'ZNotes · IGCSE',
    url: 'https://znotes.org/caie/igcse/',
    category: 'igcse',
    description: '社区维护的 CAIE IGCSE 笔记、知识点与练习入口，适合快速复习和查漏补缺。',
    tags: ['Notes', 'CAIE', 'Quiz'],
    source: 'bookmark',
    featured: true,
  },
  {
    name: 'PapaCambridge Past Papers',
    url: 'https://pastpapers.papacambridge.com/',
    category: 'igcse',
    description: '覆盖多个考试局与科目的历年试卷库，可作为真题检索的备用来源。',
    tags: ['Past Papers', '多考试局'],
    source: 'bookmark',
  },
  {
    name: 'RevisionTown IGCSE',
    url: 'https://revisiontown.com/igcse-past-papers/',
    category: 'igcse',
    description: '按 IGCSE 科目汇总的真题入口，适合快速跳转至对应资料目录。',
    tags: ['Past Papers', '分类目录'],
    source: 'bookmark',
  },
  {
    name: 'Save My Exams · CIE Biology',
    url: 'https://www.savemyexams.com/igcse/biology/cie/23/revision-notes/',
    category: 'igcse',
    description: 'CIE IGCSE Biology 分章节复习笔记；部分内容可能需要账户或订阅。',
    tags: ['Biology', 'Revision Notes'],
    source: 'bookmark',
  },
  {
    name: 'Physics & Maths Tutor · Biology',
    url: 'https://www.physicsandmathstutor.com/biology-revision/igcse-cie/',
    category: 'igcse',
    description: 'CIE IGCSE Biology 的专题笔记、题目与复习材料集合。',
    tags: ['Biology', 'Topic Questions'],
    source: 'bookmark',
  },
  {
    name: 'Cambridge International AS & A Level',
    url: 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-advanced/cambridge-international-as-and-a-levels/subjects/',
    category: 'alevel-cie',
    description: 'Cambridge 官方科目目录，可查 syllabus、样卷、past papers 与官方支持资料。',
    tags: ['Official', 'Syllabus', 'Past Papers'],
    source: 'official',
    featured: true,
  },
  {
    name: 'ZNotes · Subjects',
    url: 'https://znotes.org/subjects/',
    category: 'alevel-cie',
    description: '从科目总目录进入 CAIE AS & A Level 社区笔记和学习小组。',
    tags: ['Notes', 'Community'],
    source: 'bookmark',
  },
  {
    name: 'Pearson Edexcel International A Level',
    url: 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels.html',
    category: 'alevel-edexcel',
    description: 'Pearson 官方 IAL 入口，按科目查 specification、考试材料与资格说明。',
    tags: ['Official', 'IAL', 'Specification'],
    source: 'official',
    featured: true,
  },
  {
    name: 'IELTS Official Preparation',
    url: 'https://ielts.org/take-a-test/preparation-resources',
    category: 'ielts',
    description: 'IELTS 官方备考资源，包含样题、写作讲解、课程、讲座与练习材料。',
    tags: ['Official', 'Practice Tests', 'Writing'],
    source: 'official',
    featured: true,
  },
  {
    name: '雅思中文官方网站 · 备考指南',
    url: 'https://www.chinaielts.org/prepare',
    category: 'ielts',
    description: '中文 IELTS 备考指南与考试信息，适合了解考试结构和备考路径。',
    tags: ['中文', 'Official', '指南'],
    source: 'bookmark',
  },
  {
    name: 'ChatGPT',
    url: 'https://chatgpt.com/',
    category: 'ai',
    description: '适合概念讲解、写作反馈、代码分析与基于文件的学习对话；重要结论仍需核对原始资料。',
    tags: ['OpenAI', '文件分析', '写作', '编程'],
    source: 'official',
    featured: true,
  },
  {
    name: 'Claude',
    url: 'https://claude.ai/',
    category: 'ai',
    description: '适合阅读长文档、整理思路、逐步讲解复杂概念，以及生成可交互的学习内容。',
    tags: ['Anthropic', '长文档', '分析', '编程'],
    source: 'official',
    featured: true,
  },
  {
    name: 'Google Gemini',
    url: 'https://gemini.google.com/',
    category: 'ai',
    description: 'Google 的多模态 AI 助手，适合结合图片、网页与 Google 服务完成学习任务。',
    tags: ['Google', '多模态', 'Research'],
    source: 'official',
    featured: true,
  },
  {
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com/',
    category: 'ai',
    description: '中文友好的通用 AI 助手，可用于推理、数学与代码问题的讨论和解题复盘。',
    tags: ['中文', 'Reasoning', 'Math', 'Code'],
    source: 'official',
  },
  {
    name: 'Qwen Chat',
    url: 'https://chat.qwen.ai/',
    category: 'ai',
    description: '通义千问官方聊天入口，适合中文学习、多模态理解、文档整理与编程辅助。',
    tags: ['Alibaba', '中文', '多模态'],
    source: 'official',
  },
  {
    name: 'Perplexity',
    url: 'https://www.perplexity.ai/',
    category: 'ai',
    description: '以搜索与引用来源为核心的 AI 问答，适合建立资料线索；引用内容仍应打开原文确认。',
    tags: ['AI Search', 'Sources', 'Research'],
    source: 'added',
  },
  {
    name: 'Khan Academy',
    url: 'https://www.khanacademy.org/',
    category: 'math-science',
    description: '覆盖中小学到大学基础数学、科学、经济与计算机课程，包含视频和分级练习。',
    tags: ['Math', 'Science', 'Practice'],
    source: 'official',
    featured: true,
  },
  {
    name: 'Wolfram|Alpha',
    url: 'https://www.wolframalpha.com/',
    category: 'math-science',
    description: '用于计算、绘图、单位换算和查询数学科学事实；适合验证过程而不是只抄最终答案。',
    tags: ['Calculator', 'Algebra', 'Science'],
    source: 'official',
  },
  {
    name: 'GeoGebra',
    url: 'https://www.geogebra.org/',
    category: 'math-science',
    description: '免费的几何、代数、函数图像、微积分与 3D 数学可视化工具。',
    tags: ['Geometry', 'Graphing', 'Visualization'],
    source: 'official',
  },
  {
    name: 'PhET Interactive Simulations',
    url: 'https://phet.colorado.edu/',
    category: 'math-science',
    description: 'University of Colorado Boulder 提供的交互式物理、化学、数学和地球科学模拟。',
    tags: ['Physics', 'Chemistry', 'Simulation'],
    source: 'official',
  },
  {
    name: 'CS50P · Python',
    url: 'https://www.youtube.com/watch?v=nLRL_NcnK-4',
    category: 'computer',
    description: 'Harvard CS50 的 Python 完整课程视频，适合系统入门编程。',
    tags: ['Python', 'YouTube', 'Course'],
    source: 'bookmark',
    featured: true,
  },
  {
    name: 'C++ Full Course',
    url: 'https://www.youtube.com/watch?v=-TkoO8Z07hI',
    category: 'computer',
    description: '从基础语法开始的 C++ 长课程，适合作为入门路线或复习索引。',
    tags: ['C++', 'YouTube', 'Course'],
    source: 'bookmark',
  },
  {
    name: '洛谷',
    url: 'https://www.luogu.com.cn/',
    category: 'computer',
    description: '中文算法题库、在线评测与计算机科学学习社区。',
    tags: ['算法', 'OJ', '中文'],
    source: 'bookmark',
  },
  {
    name: 'W3Schools',
    url: 'https://www.w3schools.com/',
    category: 'computer',
    description: '网页开发与常见编程语言的交互式入门教程和语法参考。',
    tags: ['Web', 'Reference', 'Tutorial'],
    source: 'bookmark',
  },
  {
    name: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/',
    category: 'courses',
    description: '免费浏览 MIT 各院系课程资料，常见内容包括 syllabus、讲义、作业、考试与公开视频。',
    tags: ['MIT', 'Open Access', 'University'],
    source: 'official',
    featured: true,
  },
  {
    name: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/',
    category: 'courses',
    description: '免费的项目式编程课程，覆盖网页开发、Python、数据分析和机器学习基础。',
    tags: ['Coding', 'Projects', 'Free'],
    source: 'official',
  },
  {
    name: 'edX',
    url: 'https://www.edx.org/',
    category: 'courses',
    description: '汇集大学和机构在线课程；部分课程可免费旁听，证书或评分功能可能收费。',
    tags: ['MOOC', 'University', 'Courses'],
    source: 'added',
  },
  {
    name: 'Coursera',
    url: 'https://www.coursera.org/courses',
    category: 'courses',
    description: '大学和企业课程平台，适合结构化学习；免费旁听和付费项目因课程而异。',
    tags: ['MOOC', 'Certificates', 'Courses'],
    source: 'added',
  },
  {
    name: 'BBC Learning English',
    url: 'https://www.bbc.co.uk/learningenglish/',
    category: 'language',
    description: '按水平提供听力、口语、词汇、语法、新闻英语与短时长课程。',
    tags: ['Listening', 'Vocabulary', 'News'],
    source: 'official',
    featured: true,
  },
  {
    name: 'Cambridge Dictionary',
    url: 'https://dictionary.cambridge.org/',
    category: 'language',
    description: '查询英英释义、英美发音、搭配和真实例句，适合 IELTS 写作与词汇积累。',
    tags: ['Dictionary', 'Pronunciation', 'Examples'],
    source: 'official',
  },
  {
    name: 'YouGlish',
    url: 'https://youglish.com/',
    category: 'language',
    description: '从真实视频片段中检索单词和短语的发音与上下文用法。',
    tags: ['Pronunciation', 'Context', 'Video'],
    source: 'added',
  },
  {
    name: 'AnkiWeb',
    url: 'https://ankiweb.net/',
    category: 'language',
    description: '基于间隔重复的记忆卡同步服务，适合词汇、定义、公式和知识点长期复习。',
    tags: ['SRS', 'Flashcards', 'Memory'],
    source: 'official',
  },
  {
    name: 'Google Scholar',
    url: 'https://scholar.google.com/',
    category: 'research',
    description: '检索论文、书籍、会议文章和引用关系，适合从综述或高被引资料开始研究。',
    tags: ['Papers', 'Citations', 'Academic'],
    source: 'official',
    featured: true,
  },
  {
    name: 'arXiv',
    url: 'https://arxiv.org/',
    category: 'research',
    description: '数学、物理、计算机科学等领域的开放预印本平台；内容通常尚未经过正式同行评审。',
    tags: ['Preprints', 'STEM', 'Open Access'],
    source: 'official',
  },
  {
    name: 'Wikipedia',
    url: 'https://www.wikipedia.org/',
    category: 'research',
    description: '快速建立主题全貌与关键词的起点；正式写作时应继续查看页面引用的原始来源。',
    tags: ['Encyclopedia', 'Overview', 'References'],
    source: 'official',
  },
  {
    name: 'Internet Archive',
    url: 'https://archive.org/',
    category: 'research',
    description: '非营利数字图书馆，可查历史网页、书籍、音视频与软件档案。',
    tags: ['Archive', 'Books', 'Wayback Machine'],
    source: 'official',
  },
  {
    name: 'NotebookLM',
    url: 'https://notebooklm.google.com/',
    category: 'tools',
    description: '把课程资料、PDF 与笔记整理为可追溯来源的 AI 学习空间。',
    tags: ['AI', 'Notes', 'Research'],
    source: 'bookmark',
    featured: true,
  },
  {
    name: 'paper.sc',
    url: 'https://paper.sc/',
    category: 'tools',
    description: '简洁的在线文档与写作工具，可用于快速记录、整理和分享内容。',
    tags: ['Writing', 'Notes'],
    source: 'bookmark',
  },
  {
    name: 'YouTube',
    url: 'https://www.youtube.com/',
    category: 'tools',
    description: '寻找学科讲解、公开课与编程长课程；建议配合播放列表建立学习路径。',
    tags: ['Video', 'Courses'],
    source: 'bookmark',
  },
];
