export type ScriptCategory =
  | 'study'
  | 'focus'
  | 'communication'
  | 'portal'
  | 'video'
  | 'reading'
  | 'developer'
  | 'productivity'
  | 'social'
  | 'privacy';

export type ScriptSafety = 'local' | 'selected' | 'caution';

export interface UserscriptEntry {
  id: string;
  name: string;
  version: string;
  category: ScriptCategory;
  description: string;
  sites: string[];
  features: string[];
  file?: string;
  installUrl?: string;
  sourceUrl?: string;
  license?: string;
  external?: boolean;
  caution?: string;
  sourceLabel?: 'JackYun' | 'GitHub' | 'Greasy Fork' | '官方';
  safety?: ScriptSafety;
  permissions?: string[];
  updated?: string;
  popularity?: string;
}

export const USERSCRIPTS: UserscriptEntry[] = [
  {
    id: 'jackyun-portal-companion',
    name: 'JackYun Portal Companion',
    version: '1.0.0',
    category: 'portal',
    description: '本站自研的学习网站助手：只在设备本地统计有效使用时间，提供每日/七日报告、目标、专注计时和数据备份。',
    sites: ['JackYun Portal', '40+ 学习与 AI 网站'],
    features: ['有效时间统计', '每日与七日报告', '专注计时', '目标进度', 'JSON 导入导出', '资源页时长徽章'],
    file: '/userscripts/jackyun-portal-companion.user.js',
    license: 'MIT',
    sourceLabel: 'JackYun',
    safety: 'local',
    permissions: ['GM_getValue', 'GM_setValue', '无网络请求'],
  },
  {
    id: 'znotes-quiz-helper',
    name: 'ZNotes 刷题助手',
    version: '2.3',
    category: 'study',
    description: '使用数字键 1–4 选择答案、Enter 进入下一题，并以轻量弹窗提示对错。',
    sites: ['znotes.org'],
    features: ['键盘作答', '对错提示', '不改动原页面布局'],
    file: '/userscripts/znotes-quiz-helper.user.js',
  },
  {
    id: 'bestexam-batch-downloader',
    name: 'BestExamHelp Batch Downloader',
    version: '1.1',
    category: 'study',
    description: '识别试卷列表并尝试把页面链接转换为 PDF，提供批量下载按钮。',
    sites: ['bestexamhelp.com'],
    features: ['批量下载', 'PHP → PDF 链接转换', '下载间隔保护'],
    file: '/userscripts/bestexam-batch-downloader.user.js',
    caution: '一次会发起多个下载，请先确认浏览器的多文件下载权限。',
  },
  {
    id: 'save-my-exams-console',
    name: 'Save My Exams 终极控制台',
    version: '30.0',
    category: 'study',
    description: '面向 Save My Exams 的调试与下载控制台，包含模块测试、动画预览和日志工具。',
    sites: ['savemyexams.com', 'savemyexams.co.uk'],
    features: ['调试控制台', '流式下载', '模块测试'],
    file: '/userscripts/save-my-exams-console.user.js',
  },
  {
    id: 'ultimate-focus',
    name: "Jack's Ultimate Focus",
    version: '24.9',
    category: 'focus',
    description: '在 YouTube 与指定学习网站记录专注时间，管理学习关键词并自动合并历史统计。',
    sites: ['youtube.com', 'koolearn.com'],
    features: ['专注统计', '关键词分类', '历史数据合并'],
    file: '/userscripts/jacks-ultimate-focus.user.js',
  },
  {
    id: 'timezone-panel',
    name: 'Timezone Panel · Bilibili & Discord',
    version: '5.1.0',
    category: 'communication',
    description: '在 Bilibili 私信与 Discord 消息旁显示 CST（UTC−6）时间，并提供浮动时区面板。',
    sites: ['message.bilibili.com', 'discord.com'],
    features: ['时区换算', '消息时间徽章', '浮动面板'],
    file: '/userscripts/timezone-panel.user.js',
  },
  {
    id: 'discord-image-shield',
    name: 'Discord 图片拦截器 · Image Shield',
    version: '2.0.0',
    category: 'communication',
    description: '在学校或工作场景隐藏 Discord 聊天图片，支持占位/模糊和单张解锁。',
    sites: ['discord.com', 'ptb.discord.com', 'canary.discord.com'],
    features: ['图片拦截', '单张解锁', '模糊模式'],
    file: '/userscripts/discord-image-shield.user.js',
  },
  {
    id: 'relax-interpreter',
    name: "Jack's Relax Interpreter (Lite)",
    version: '1.2',
    category: 'portal',
    description: '为旧版 Relax 页面中的 AI 指令标签添加中文解释，不增加额外控制台界面。',
    sites: ['yunfanshi.github.io/Relax.html'],
    features: ['指令解释', '即时监听', '轻量 UI'],
    file: '/userscripts/relax-interpreter.user.js',
  },
  {
    id: 'youtube-alchemy',
    name: 'YouTube Alchemy',
    version: 'GitHub',
    category: 'study',
    description: '面向 YouTube 学习场景的社区增强脚本，提供字幕与 transcript 导出、播放速度、默认字幕语言、隐藏 Shorts 等大量选项。',
    sites: ['youtube.com'],
    features: ['Transcript 导出', '播放控制', '字幕语言', '隐藏干扰内容'],
    installUrl: 'https://raw.githubusercontent.com/TimMacy/YouTubeAlchemy/main/YouTubeAlchemy.js',
    sourceUrl: 'https://github.com/TimMacy/YouTubeAlchemy',
    license: 'AGPL-3.0',
    external: true,
    caution: '第三方项目会独立更新；安装前请在 GitHub 查看最新说明和权限。',
  },
  {
    id: 'immersive-translate',
    name: '沉浸式翻译 · Userscript',
    version: '官方发布版',
    category: 'study',
    description: '为网页、PDF、EPUB 和字幕提供双语对照翻译，适合阅读英文资料和进行语言学习。',
    sites: ['多网站', 'PDF', 'EPUB'],
    features: ['双语对照', 'PDF 翻译', '字幕翻译', '输入框翻译'],
    installUrl: 'https://download.immersivetranslate.com/immersive-translate.user.js',
    sourceUrl: 'https://github.com/immersive-translate/immersive-translate',
    license: '非开源发布版',
    external: true,
    caution: '翻译内容可能发送给你选择的翻译服务；该 GitHub 仓库用于发布版本，不包含当前源代码。',
  },
  {
    id: 'bilibili-subtitle-download',
    name: 'Bilibili International Subtitle Downloader',
    version: 'GitHub',
    category: 'study',
    description: '为 Bilibili International 视频提供字幕下载入口，适合保存课程字幕后做笔记或语言分析。',
    sites: ['bilibili.tv'],
    features: ['字幕下载', '课程笔记', 'Tampermonkey'],
    installUrl: 'https://raw.githubusercontent.com/AdvMaple/bilibili-subtitle-download-plugin/feature/download.user.js',
    sourceUrl: 'https://github.com/AdvMaple/bilibili-subtitle-download-plugin',
    license: '仓库未明确标注',
    external: true,
    caution: '这是较早的社区脚本，主要面向 Bilibili International；网页结构变化后可能失效。',
  },
  {
    id: 'html5-video-tools',
    name: 'HTML5 视频播放工具',
    version: '2.0.2',
    category: 'video',
    description: '跨站视频快捷键工具，统一提供倍速、逐帧、画中画、截图、旋转和网页全屏等播放控制。',
    sites: ['YouTube', 'Bilibili', '腾讯视频', '爱奇艺', 'Twitch', '斗鱼', '虎牙'],
    features: ['倍速与逐帧', '截图与画中画', '网页全屏', '跨站快捷键'],
    installUrl: 'https://update.greasyfork.org/scripts/30545/HTML5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%B7%A5%E5%85%B7.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/30545-html5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%B7%A5%E5%85%B7',
    sourceLabel: 'Greasy Fork',
    license: 'MIT',
    external: true,
    safety: 'selected',
    permissions: ['跨多个视频网站', '键盘快捷键'],
    updated: '2025-08-06',
    popularity: 'Greasy Fork 约 128 万次安装',
  },
  {
    id: 'youtube-cpu-tamer',
    name: 'YouTube CPU Tamer',
    version: '2025.02.24.0',
    category: 'video',
    description: '调整 YouTube 页面计时任务的执行方式，减少长时间播放时的 CPU 占用和页面卡顿。',
    sites: ['youtube.com'],
    features: ['降低后台负载', '长视频优化', '无需外部服务'],
    installUrl: 'https://update.greasyfork.org/scripts/431573/YouTube%20CPU%20Tamer%20by%20AnimationFrame.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/431573-youtube-cpu-tamer-by-animationframe',
    sourceLabel: 'Greasy Fork',
    license: 'MIT',
    external: true,
    safety: 'caution',
    permissions: ['youtube.com', '覆盖页面计时器'],
    updated: '2025-02-24',
    caution: '会改变 YouTube 的计时机制并依赖硬件加速；如出现播放或扩展冲突请停用。',
  },
  {
    id: 'general-url-cleaner',
    name: 'General URL Cleaner Revived',
    version: '5.1.0',
    category: 'privacy',
    description: '移除分享链接中的常见跟踪参数，减少把广告标识符和来源信息继续传播给其他网站。',
    sites: ['Google', 'YouTube', 'Amazon', 'Facebook', 'LinkedIn', 'Reddit', 'TikTok'],
    features: ['清理跟踪参数', '复制链接更简洁', '按支持站点生效'],
    installUrl: 'https://update.greasyfork.org/scripts/432387/General%20URL%20Cleaner%20Revived.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/432387-general-url-cleaner-revived',
    sourceLabel: 'Greasy Fork',
    license: 'GPL-3+',
    external: true,
    safety: 'selected',
    permissions: ['多个支持站点', 'URL 处理'],
    updated: '2026-07-11',
  },
  {
    id: 'ac-baidu',
    name: 'AC-baidu 搜索净化',
    version: 'Greasy Fork',
    category: 'productivity',
    description: '整理百度、Google、必应和搜狗搜索结果，去除跳转链接、补充网站图标并提供结果布局选项。',
    sites: ['Baidu', 'Google', 'Bing', 'Sogou'],
    features: ['直达链接', '结果净化', '网站图标', '布局增强'],
    installUrl: 'https://update.greasyfork.org/scripts/14178/AC-baidu-google_sogou_bing_RedirectRemove_favicon_adaway_TwoLine.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'selected',
    permissions: ['主流搜索引擎', '修改搜索结果页面'],
    caution: '搜索引擎页面更新可能影响过滤规则；发现结果缺失时可临时停用。',
  },
  {
    id: 'zhihu-enhancement',
    name: '知乎增强',
    version: 'Greasy Fork',
    category: 'reading',
    description: '为知乎提供阅读净化、内容过滤、快捷操作和界面调整，适合长时间资料检索。',
    sites: ['zhihu.com'],
    features: ['沉浸阅读', '内容过滤', '快捷操作', '界面整理'],
    installUrl: 'https://update.greasyfork.org/scripts/419081/%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/419081-zhihu-enhancement',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'selected',
    permissions: ['zhihu.com', '页面内容与样式'],
    updated: '2026-08-05',
    popularity: 'Greasy Fork 约 76 万次安装',
  },
  {
    id: 'csdn-optimize',
    name: 'CSDN 阅读优化',
    version: 'Greasy Fork',
    category: 'developer',
    description: '简化 CSDN 文章页面、改善代码阅读与复制体验，并减少与正文无关的视觉干扰。',
    sites: ['csdn.net'],
    features: ['沉浸阅读', '代码复制', '页面净化', '样式优化'],
    installUrl: 'https://greasyfork.org/en/scripts/471071-csdn-optimize-beautify-simplify',
    sourceUrl: 'https://greasyfork.org/en/scripts/471071-csdn-optimize-beautify-simplify',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'selected',
    permissions: ['csdn.net', '页面内容与样式'],
    updated: '2024-10-23',
    caution: '当前条目更新较早，安装前请查看 Greasy Fork 最近反馈。',
  },
  {
    id: 'github-internationalization',
    name: 'GitHub 中文化插件',
    version: 'Greasy Fork',
    category: 'developer',
    description: '翻译 GitHub 常用界面文本，保留代码、仓库名称和技术内容本身，降低初学者的操作门槛。',
    sites: ['github.com'],
    features: ['界面中文化', '动态内容翻译', '保留代码原文'],
    installUrl: 'https://update.greasyfork.org/scripts/407485/GitHub%20Internationalization.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/407485-github-internationalization',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'selected',
    permissions: ['github.com', '界面文本替换'],
    updated: '2026-06-16',
    popularity: 'Greasy Fork 约 14 万次安装',
  },
  {
    id: 'my-prompt',
    name: 'My Prompt · AI 提示词管理',
    version: 'Greasy Fork',
    category: 'productivity',
    description: '在多个 AI 对话网站统一管理提示词、快捷键和常用附件，减少重复输入。',
    sites: ['ChatGPT', 'Claude', 'Gemini', 'DeepSeek', 'Grok'],
    features: ['提示词库', '快捷输入', '多 AI 平台', '附件模板'],
    installUrl: 'https://update.greasyfork.org/scripts/549921/My%20Prompt.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/549921-my-prompt',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'caution',
    permissions: ['多个 AI 对话网站', '读取并填充输入框'],
    updated: '2026-08-04',
    caution: '提示词可能包含隐私信息；不要在脚本内保存密码、API Key 或未脱敏的个人资料。',
  },
  {
    id: 'reddit-plus-plus',
    name: 'Reddit++',
    version: 'Greasy Fork',
    category: 'social',
    description: '整理 Reddit 界面并提供关键词过滤，让技术社区和兴趣社区的浏览更专注。',
    sites: ['reddit.com'],
    features: ['关键词过滤', '界面清理', '阅读增强'],
    installUrl: 'https://update.greasyfork.org/scripts/490046/Reddit%2B%2B.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/490046-reddit',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'selected',
    permissions: ['reddit.com', '页面内容与样式'],
    updated: '2026-06-20',
  },
  {
    id: 'bilibili-comment-search',
    name: 'Bilibili 评论搜索',
    version: 'Greasy Fork',
    category: 'video',
    description: '在 Bilibili 视频评论区增加搜索能力，便于从课程讨论或长评论区快速定位关键词。',
    sites: ['bilibili.com'],
    features: ['评论关键词搜索', '学习讨论定位', '页面内操作'],
    installUrl: 'https://update.greasyfork.org/scripts/467863/Bilibili%20%E8%AF%84%E8%AE%BA%E6%90%9C%E7%B4%A2.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/467863-bilibili-%E8%AF%84%E8%AE%BA%E6%90%9C%E7%B4%A2',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'selected',
    permissions: ['bilibili.com', '读取页面评论'],
    updated: '2025-07-09',
  },
  {
    id: 'ig-helper',
    name: 'IG Helper',
    version: 'Greasy Fork',
    category: 'social',
    description: '为 Instagram 网页版补充媒体保存入口，适合保存自己拥有权利或已获授权的素材。',
    sites: ['instagram.com'],
    features: ['图片保存', '视频保存', '页面快捷入口'],
    installUrl: 'https://update.greasyfork.org/scripts/404535/IG%20Helper.user.js',
    sourceUrl: 'https://greasyfork.org/en/scripts/404535-ig-helper',
    sourceLabel: 'Greasy Fork',
    external: true,
    safety: 'caution',
    permissions: ['instagram.com', '访问页面媒体地址'],
    updated: '2026-07-30',
    popularity: 'Greasy Fork 约 5 万次安装',
    caution: '仅下载你有权保存的内容，并遵守平台条款、版权与当地法律。',
  },
];
