import { createClient } from '@/lib/supabase/server';
import Link from 'next/link';

export const metadata = { title: '学习活动 · JackYun Portal' };

export default async function ActivityPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const start = new Date(); start.setDate(start.getDate() - 29);
  const [{ data: rows }, { data: queue }, { data: devices }, { data: setting }] = await Promise.all([
    supabase.from('companion_activity_daily').select('activity_date, hostname, category, active_seconds, visits').eq('user_id', user?.id ?? '').gte('activity_date', start.toISOString().slice(0, 10)).order('activity_date'),
    supabase.from('companion_learning_queue').select('id, title, url, hostname, category, status, created_at').eq('user_id', user?.id ?? '').neq('status', 'archived').order('created_at', { ascending: false }).limit(8),
    supabase.from('companion_devices').select('id, name, platform, extension_version, last_seen_at, revoked_at').eq('user_id', user?.id ?? '').order('last_seen_at', { ascending: false }),
    supabase.from('user_settings').select('value').eq('user_id', user?.id ?? '').eq('key', 'companion_preferences').maybeSingle(),
  ]);
  const records = rows ?? [];
  const total = records.reduce((sum, row) => sum + Number(row.active_seconds || 0), 0);
  const today = new Date().toLocaleDateString('en-CA');
  const todayTotal = records.filter((row) => row.activity_date === today).reduce((sum, row) => sum + Number(row.active_seconds || 0), 0);
  const goal = Number((setting?.value as { goalMinutes?: number } | null)?.goalMinutes || 120);
  const bySite = Object.entries(records.reduce<Record<string, number>>((result, row) => { result[row.hostname] = (result[row.hostname] || 0) + Number(row.active_seconds || 0); return result; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 10);
  const byCategory = Object.entries(records.reduce<Record<string, number>>((result, row) => { result[row.category] = (result[row.category] || 0) + Number(row.active_seconds || 0); return result; }, {})).sort((a, b) => b[1] - a[1]);
  const days = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (6 - index)); const key = date.toLocaleDateString('en-CA'); return { key, seconds: records.filter((row) => row.activity_date === key).reduce((sum, row) => sum + Number(row.active_seconds || 0), 0) }; });
  const maximum = Math.max(1, ...days.map((day) => day.seconds));

  return <div className="page-enter mx-auto max-w-6xl pb-10"><header className="flex flex-col gap-4 border-b border-[var(--card-border)] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#1a73e8]">Companion</p><h1 className="mt-2 text-3xl font-bold tracking-[-.04em]">学习活动</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">最近 30 天的域名级有效学习时间与同步设备。</p></div><Link href="/settings?section=companion" className="rounded-xl border border-[var(--card-border)] px-4 py-2.5 text-sm font-semibold">管理 Companion</Link></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-3"><article className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><p className="text-xs text-[var(--muted-foreground)]">今天</p><strong className="mt-2 block text-3xl">{Math.round(todayTotal / 60)}m</strong><div className="mt-3 h-2 overflow-hidden rounded-full bg-[var(--background)]"><i className="block h-full bg-[#34a853]" style={{ width: `${Math.min(100, todayTotal / (goal * 60) * 100)}%` }} /></div></article><article className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><p className="text-xs text-[var(--muted-foreground)]">30 天总计</p><strong className="mt-2 block text-3xl">{Math.round(total / 360) / 10}h</strong></article><article className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><p className="text-xs text-[var(--muted-foreground)]">活跃设备</p><strong className="mt-2 block text-3xl">{(devices ?? []).filter((device) => !device.revoked_at).length}</strong></article></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_1fr]"><article className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="font-semibold">最近 7 天</h2><div className="mt-5 flex h-48 items-end gap-3">{days.map((day) => <div key={day.key} className="flex flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] text-[var(--muted-foreground)]">{Math.round(day.seconds / 60)}m</span><i className="w-full rounded-t-lg bg-[#8ab4f8]" style={{ height: `${Math.max(4, day.seconds / maximum * 135)}px` }} /><time className="text-[10px] text-[var(--muted-foreground)]">{day.key.slice(5).replace('-', '/')}</time></div>)}</div></article><article className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="font-semibold">学习类别</h2><div className="mt-4 space-y-3">{byCategory.map(([name, seconds]) => <div key={name}><div className="flex justify-between text-sm"><span>{name}</span><span className="text-[var(--muted-foreground)]">{Math.round(seconds / 60)}m</span></div><div className="mt-1 h-1.5 rounded-full bg-[var(--background)]"><i className="block h-full rounded-full bg-[#1a73e8]" style={{ width: `${total ? seconds / total * 100 : 0}%` }} /></div></div>)}</div></article></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="font-semibold">常用学习网站</h2><ol className="mt-4 space-y-3">{bySite.map(([hostname, seconds], index) => <li key={hostname} className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[var(--background)] text-xs font-bold">{index + 1}</span><span className="min-w-0 flex-1 truncate">{hostname}</span><time className="text-sm text-[var(--muted-foreground)]">{Math.round(seconds / 60)}m</time></li>)}</ol></article><article className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="font-semibold">稍后学习</h2><div className="mt-4 space-y-3">{(queue ?? []).map((item) => <a key={item.id} href={item.url} target="_blank" rel="noopener noreferrer" className="block rounded-xl border border-[var(--card-border)] p-3 hover:border-[#1a73e8]"><strong className="block truncate text-sm">{item.title}</strong><span className="mt-1 block text-xs text-[var(--muted-foreground)]">{item.category} · {item.hostname}</span></a>)}{!queue?.length && <p className="text-sm text-[var(--muted-foreground)]">在扩展中把页面加入“稍后学习”，这里会自动同步。</p>}</div></article></section>
  </div>;
}
